# ==================== 🎯 TASK TYPES ====================
- name: "type-bug"
  color: "d73a4a"
  description: "Ошибки компиляции или баги в плагинах"

- name: "type-feature"
  color: "a2eeef"
  description: "Новые функции плагинов"

- name: "type-refactor"
  color: "d4c5f9"
  description: "Рефакторинг кода"

- name: "type-build"
  color: "0075ca"
  description: "Задачи сборки и CI/CD"

- name: "type-docs"
  color: "0075ca"
  description: "Документация"

- name: "type-test"
  color: "d93f0b"
  description: "Тестирование"

# ==================== ⚡ PRIORITIES ====================
- name: "priority-critical"
  color: "b60205"
  description: "Критический приоритет - блокирует разработку"

- name: "priority-high"
  color: "d93f0b"
  description: "Высокий приоритет - важные функции"

- name: "priority-medium"
  color: "0e8a16"
  description: "Средний приоритет - обычная разработка"

- name: "priority-low"
  color: "ededed"
  description: "Низкий приоритет - улучшения"

# ==================== 🧩 COMPONENTS ====================
- name: "component-compiler"
  color: "bfdadc"
  description: "Связано с AMXX компилятором"

- name: "component-ci-cd"
  color: "bfd4f2"
  description: "Связано с CI/CD пайплайном"

- name: "component-plugins"
  color: "d4c5f9"
  description: "Связано с разработкой плагинов"

- name: "component-docs"
  color: "0075ca"
  description: "Связано с документацией"

- name: "component-versioning"
  color: "fbca04"
  description: "Связано с системой версионирования"

# ==================== 🚀 RELEASE STAGES ====================
- name: "stage-dev"
  color: "5319e7"
  description: "Разработка в dev ветке"

- name: "stage-alpha"
  color: "5319e7"
  description: "Альфа-тестирование"

- name: "stage-beta"
  color: "5319e7"
  description: "Бета-тестирование"

- name: "stage-rc"
  color: "5319e7"
  description: "Релиз-кандидат"

- name: "stage-release"
  color: "5319e7"
  description: "Финальный релиз"

- name: "stage-hotfix"
  color: "5319e7"
  description: "Экстренный хотфикс"

# ==================== 📊 VERSIONING ====================
- name: "version-major"
  color: "fbca04"
  description: "Мажорное изменение версии (X.0.0)"

- name: "version-minor"
  color: "fbca04"
  description: "Минорное изменение версии (0.Y.0)"

- name: "version-patch"
  color: "fbca04"
  description: "Патч версии (0.0.Z)"

# ==================== 🔄 WORKFLOW ====================
- name: "workflow-auto"
  color: "006b75"
  description: "Автоматически назначенная метка"

- name: "workflow-needs-review"
  color: "fbca04"
  description: "Требует ревью"

- name: "workflow-in-progress"
  color: "0052cc"
  description: "В процессе работы"

- name: "workflow-completed"
  color: "0e8a16"
  description: "Завершено"