name: Auto Label Issues and PRs

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: 🏷️ Auto-label issues and PRs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            module.exports = async ({ github, context }) => {
              try {
                // Безопасное получение данных
                const issueData = context.payload.issue;
                const prData = context.payload.pull_request;
                
                if (!issueData && !prData) {
                  console.log('❌ No issue or PR data found');
                  return;
                }

                const target = issueData || prData;
                const { title, body, number, labels = [] } = target;
                const type = issueData ? 'issue' : 'pull_request';

                if (!title) {
                  console.log(`⚠️ No title found for ${type} #${number}`);
                  return;
                }

                console.log(`📋 Processing ${type}: "${title}" (#${number})`);

                const content = `${title} ${body || ''}`.toLowerCase();
                const newLabels = new Set(labels.map(label => label.name));

                // Определение меток
                const rules = [
                  { keywords: ['bug', 'ошибка', 'fix', 'исправление'], label: 'bug' },
                  { keywords: ['feature', 'функция', 'улучшение', 'новая возможность'], label: 'enhancement' },
                  { keywords: ['doc', 'documentation', 'документация'], label: 'documentation' },
                  { keywords: ['urgent', 'срочно', 'critical', 'критично'], label: 'priority-high' },
                  { keywords: ['question', 'вопрос', 'help', 'помощь'], label: 'question' },
                  { keywords: ['refactor', 'рефакторинг'], label: 'refactor' }
                ];

                rules.forEach(rule => {
                  if (rule.keywords.some(keyword => content.includes(keyword))) {
                    newLabels.add(rule.label);
                  }
                });

                // Для PR добавляем размер
                if (prData) {
                  const { additions, deletions } = prData;
                  const totalChanges = additions + deletions;
                  
                  if (totalChanges > 150) newLabels.add('size-large');
                  else if (totalChanges > 50) newLabels.add('size-medium');
                  else if (totalChanges > 0) newLabels.add('size-small');
                }

                // Удаляем существующие метки размера если добавляем новую
                if (newLabels.has('size-large') || newLabels.has('size-medium') || newLabels.has('size-small')) {
                  newLabels.delete('size-large');
                  newLabels.delete('size-medium'); 
                  newLabels.delete('size-small');
                  
                  if (totalChanges > 150) newLabels.add('size-large');
                  else if (totalChanges > 50) newLabels.add('size-medium');
                  else newLabels.add('size-small');
                }

                const labelsToAdd = Array.from(newLabels);

                if (labelsToAdd.length > 0) {
                  console.log(`🏷️ Setting labels: ${labelsToAdd.join(', ')}`);
                  
                  await github.rest.issues.setLabels({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: number,
                    labels: labelsToAdd
                  });
                  
                  console.log('✅ Labels updated successfully');
                } else {
                  console.log('ℹ️ No labels to add');
                }

              } catch (error) {
                console.error('💥 Error in auto-label workflow:', error.message);
                // Не проваливаем весь workflow из-за ошибки меток
              }
            }