name: Auto Label Issues and PRs

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: 🏷️ Auto-label issues and PRs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              // Безопасное получение данных
              const issueData = context.payload.issue;
              const prData = context.payload.pull_request;
              
              if (!issueData && !prData) {
                console.log('❌ No issue or PR data found');
                return;
              }

              const target = issueData || prData;
              const { title, body, number, labels = [] } = target;
              const type = issueData ? 'issue' : 'pull_request';

              if (!title) {
                console.log(`⚠️ No title found for ${type} #${number}`);
                return;
              }

              console.log(`📋 Processing ${type}: "${title}" (#${number})`);

              const content = `${title} ${body || ''}`.toLowerCase();
              const newLabels = new Set(labels.map(label => label.name));

              // Определение меток на основе вашего labels.yml
              const rules = [
                { keywords: ['bug', 'ошибка', 'fix', 'исправление', 'баг'], label: 'bug' },
                { keywords: ['feature', 'функция', 'улучшение', 'новая возможность', 'добавить'], label: 'feature' },
                { keywords: ['refactor', 'рефакторинг', 'оптимизация', 'переработка'], label: 'refactor' },
                { keywords: ['build', 'сборка', 'ci/cd', 'compile', 'компиляция'], label: 'build' },
                { keywords: ['doc', 'documentation', 'документация', 'readme', 'инструкция'], label: 'docs' },
                { keywords: ['test', 'тест', 'testing', 'тестирование'], label: 'test' },
                { keywords: ['critical', 'критич', 'блокир', 'срочно', 'аварий'], label: 'priority-critical' },
                { keywords: ['high', 'высок', 'важн', 'приоритет'], label: 'priority-high' },
                { keywords: ['medium', 'средн', 'обычн'], label: 'priority-medium' },
                { keywords: ['low', 'низк', 'улучшен', 'неважн'], label: 'priority-low' },
                { keywords: ['compiler', 'компилятор', 'amxxpc', 'amxx'], label: 'component-compiler' },
                { keywords: ['ci/cd', 'pipeline', 'github action', 'workflow', 'автоматизация'], label: 'component-ci-cd' },
                { keywords: ['plugin', 'плагин', '.sma', '.amxx', 'модуль'], label: 'component-plugins' },
                { keywords: ['doc', 'документ', 'readme', 'wiki', 'инструкция'], label: 'component-docs' },
                { keywords: ['major', 'мажор', 'x.0.0'], label: 'version-major' },
                { keywords: ['minor', 'минор', '0.y.0'], label: 'version-minor' },
                { keywords: ['patch', 'патч', '0.0.z', 'исправление'], label: 'version-patch' },
                { keywords: ['dev', 'разработка', 'development'], label: 'stage-dev' },
                { keywords: ['alpha', 'альфа'], label: 'stage-alpha' },
                { keywords: ['beta', 'бета'], label: 'stage-beta' },
                { keywords: ['rc', 'release candidate', 'релиз-кандидат'], label: 'stage-rc' },
                { keywords: ['release', 'релиз', 'production', 'продакшен'], label: 'stage-release' },
                { keywords: ['hotfix', 'хотфикс', 'срочное исправление'], label: 'stage-hotfix' }
              ];

              rules.forEach(rule => {
                if (rule.keywords.some(keyword => content.includes(keyword))) {
                  newLabels.add(rule.label);
                }
              });

              // Для PR добавляем автоматические метки
              if (prData) {
                newLabels.add('component-plugins');
                
                const { additions, deletions } = prData;
                const totalChanges = additions + deletions;
                
                // Автоматически определяем приоритет по размеру изменений
                if (totalChanges > 500) {
                  newLabels.add('priority-critical');
                } else if (totalChanges > 200) {
                  newLabels.add('priority-high');
                } else if (totalChanges > 50) {
                  newLabels.add('priority-medium');
                } else {
                  newLabels.add('priority-low');
                }

                // Определяем размер PR
                if (totalChanges > 150) {
                  newLabels.add('size-large');
                } else if (totalChanges > 50) {
                  newLabels.add('size-medium');
                } else if (totalChanges > 0) {
                  newLabels.add('size-small');
                }
              }

              const labelsToAdd = Array.from(newLabels);

              if (labelsToAdd.length > 0) {
                console.log(`🏷️ Setting labels: ${labelsToAdd.join(', ')}`);
                
                await github.rest.issues.setLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: number,
                  labels: labelsToAdd
                });
                
                console.log('✅ Labels updated successfully');
              } else {
                console.log('ℹ️ No labels to add');
              }

            } catch (error) {
              console.error('💥 Error in auto-label workflow:', error.message);
              // Не проваливаем весь workflow из-за ошибки меток
            }