name: Auto Label Issues and PRs

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: 🏷️ Auto-label issues and PRs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          script: |
            try {
              const issueData = context.payload.issue;
              const prData = context.payload.pull_request;
              
              if (!issueData && !prData) {
                console.log('❌ No issue or PR data found');
                return;
              }

              const target = issueData || prData;
              const { title, body, number, labels = [] } = target;
              const type = issueData ? 'issue' : 'pull_request';

              if (!title) {
                console.log(`⚠️ No title found for ${type} #${number}`);
                return;
              }

              console.log(`📋 Processing ${type}: "${title}" (#${number})`);

              const content = `${title} ${body || ''}`.toLowerCase();
              const currentLabels = new Set(labels.map(label => label.name));

              // ... (остальной код auto-label) ...

              const labelsToAdd = Array.from(currentLabels);

              if (labelsToAdd.length > 0) {
                console.log(`🏷️ Setting labels: ${labelsToAdd.join(', ')}`);
                
                await github.rest.issues.setLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: number,
                  labels: labelsToAdd
                });
                
                // Create summary
                const summary = `
                ## 🏷️ Auto-Label Summary
                
                ### 📋 ${type.toUpperCase()} Information
                - **Number:** #${number}
                - **Title:** ${title}
                - **Type:** ${type}
                
                ### 📊 Labels Applied
                ${labelsToAdd.map(label => `- ${label}`).join('\n')}
                
                ### 🔍 Content Analysis
                Content processed for keyword matching.
                
                *Auto-labeled at ${new Date().toLocaleString()}*
                `;
                
                // Write to summary
                const fs = require('fs');
                fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, summary);
                
                console.log('✅ Labels updated successfully');
              } else {
                console.log('ℹ️ No labels to add');
                
                const summary = `
                ## 🏷️ Auto-Label Summary
                
                ### 📋 ${type.toUpperCase()} Information
                - **Number:** #${number}
                - **Title:** ${title}
                - **Type:** ${type}
                
                ### ℹ️ No Labels Applied
                No matching labels found based on content analysis.
                
                *Processed at ${new Date().toLocaleString()}*
                `;
                
                const fs = require('fs');
                fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, summary);
              }

            } catch (error) {
              console.error('💥 Error in auto-label workflow:', error.message);
              
              const summary = `
              ## 🏷️ Auto-Label Summary
              
              ### ❌ Error Occurred
              ${error.message}
              
              *Failed at ${new Date().toLocaleString()}*
              `;
              
              const fs = require('fs');
              fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, summary);
            }