name: Auto Label Retroactive Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Каждое воскресенье в полночь
  push:
    branches: [main]
    paths: ['.github/labels.yml']

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  retroactive-labeling:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: 🏷️ Process existing issues and PRs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          script: |
            try {
              console.log('🔍 Starting retroactive labeling of existing issues and PRs...');
              
              // Функция для обработки отдельного issue/PR
              const processItem = async (item, type) => {
                const { title, body, number, labels = [], state } = item;
                
                // Пропускаем закрытые items
                if (state === 'closed') {
                  console.log(`⏭️ Skipping closed ${type} #${number}`);
                  return;
                }

                console.log(`📋 Processing ${type} #${number}: "${title}"`);

                const content = `${title} ${body || ''}`.toLowerCase();
                const currentLabels = new Set(labels.map(label => label.name));

                // ==================== 🎯 TASK TYPES ====================
                if (content.includes('bug') || content.includes('ошибка') || content.includes('error') || content.includes('fix') || content.includes('исправление') || content.includes('баг') || content.includes('не работает')) {
                  currentLabels.add('type-bug');
                }

                if (content.includes('feature') || content.includes('функция') || content.includes('улучшение') || content.includes('новая возможность') || content.includes('добавить') || content.includes('предложение')) {
                  currentLabels.add('type-feature');
                }

                if (content.includes('refactor') || content.includes('рефакторинг') || content.includes('оптимизация') || content.includes('переработка') || content.includes('cleanup')) {
                  currentLabels.add('type-refactor');
                }

                if (content.includes('build') || content.includes('сборка') || content.includes('ci/cd') || content.includes('compile') || content.includes('компиляция') || content.includes('pipeline')) {
                  currentLabels.add('type-build');
                }

                if (content.includes('doc') || content.includes('documentation') || content.includes('документация') || content.includes('readme') || content.includes('инструкция') || content.includes('wiki')) {
                  currentLabels.add('type-docs');
                }

                if (content.includes('test') || content.includes('тест') || content.includes('testing') || content.includes('тестирование') || content.includes('проверка')) {
                  currentLabels.add('type-test');
                }

                // ==================== ⚡ PRIORITIES ====================
                if (content.includes('critical') || content.includes('критич') || content.includes('блокир') || content.includes('срочно') || content.includes('аварий') || content.includes('urgent')) {
                  currentLabels.add('priority-critical');
                } else if (content.includes('high') || content.includes('высок') || content.includes('важн') || content.includes('приоритет') || content.includes('important')) {
                  currentLabels.add('priority-high');
                } else if (content.includes('medium') || content.includes('средн') || content.includes('обычн') || content.includes('normal')) {
                  currentLabels.add('priority-medium');
                } else if (content.includes('low') || content.includes('низк') || content.includes('улучшен') || content.includes('неважн') || content.includes('minor')) {
                  currentLabels.add('priority-low');
                }

                // ==================== 🧩 COMPONENTS ====================
                if (content.includes('compiler') || content.includes('компилятор') || content.includes('amxxpc') || content.includes('amxx') || content.includes('сборк')) {
                  currentLabels.add('component-compiler');
                }

                if (content.includes('ci/cd') || content.includes('pipeline') || content.includes('github action') || content.includes('workflow') || content.includes('автоматизация') || content.includes('action')) {
                  currentLabels.add('component-ci-cd');
                }

                if (content.includes('plugin') || content.includes('плагин') || content.includes('.sma') || content.includes('.amxx') || content.includes('модуль') || content.includes('script')) {
                  currentLabels.add('component-plugins');
                }

                if (content.includes('doc') || content.includes('документ') || content.includes('readme') || content.includes('wiki') || content.includes('инструкция') || content.includes('guide')) {
                  currentLabels.add('component-docs');
                }

                if (content.includes('version') || content.includes('версия') || content.includes('semver') || content.includes('release') || content.includes('версионирование')) {
                  currentLabels.add('component-versioning');
                }

                // Для PR добавляем специфичные метки
                if (type === 'pull_request') {
                  currentLabels.add('component-plugins');
                  currentLabels.add('workflow-needs-review');
                } else {
                  currentLabels.add('workflow-auto');
                }

                const labelsToAdd = Array.from(currentLabels);

                if (labelsToAdd.length > 0) {
                  console.log(`🏷️ Setting labels for ${type} #${number}: ${labelsToAdd.join(', ')}`);
                  
                  await github.rest.issues.setLabels({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: number,
                    labels: labelsToAdd
                  });
                }
              };

              // Получаем все открытые issues
              console.log('📦 Fetching open issues...');
              const { data: issues } = await github.rest.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                per_page: 100
              });

              // Получаем все открытые PR
              console.log('📦 Fetching open pull requests...');
              const { data: pullRequests } = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                per_page: 100
              });

              // Обрабатываем issues
              let processedCount = 0;
              for (const issue of issues) {
                if (!issue.pull_request) { // Только issues, не PR
                  await processItem(issue, 'issue');
                  processedCount++;
                  // Пауза чтобы не превысить лимиты API
                  await new Promise(resolve => setTimeout(resolve, 500));
                }
              }

              // Обрабатываем PR
              for (const pr of pullRequests) {
                await processItem(pr, 'pull_request');
                processedCount++;
                // Пауза чтобы не превысить лимиты API
                await new Promise(resolve => setTimeout(resolve, 500));
              }

              console.log(`✅ Processed ${processedCount} items`);

              const summary = `
              ## 🔍 Retroactive Labeling Complete
              
              ### 📊 Processing Summary
              - **Total processed:** ${processedCount} items
              - **Issues:** ${issues.filter(i => !i.pull_request).length}
              - **Pull Requests:** ${pullRequests.length}
              
              ### ⏰ Timestamp
              ${new Date().toLocaleString()}
              
              *Automatically processed existing issues and PRs*
              `;
              
              const fs = require('fs');
              fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, summary);

            } catch (error) {
              console.error('💥 Error in retroactive labeling:', error.message);
              
              const summary = `
              ## 🔍 Retroactive Labeling Failed
              
              ### ❌ Error Occurred
              ${error.message}
              
              *Failed at ${new Date().toLocaleString()}*
              `;
              
              const fs = require('fs');
              fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, summary);
            }