name: Auto Label Issues

on:
  issues:
    types: [opened, edited]
  workflow_dispatch:

permissions:
  issues: write

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: 🔍 Analyze issue title and body
        id: labeler
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.issue.title.toLowerCase();
            const body = context.payload.issue.body.toLowerCase();
            
            const labels = [];
            
            // Determine issue type
            if (title.includes('bug') || title.includes('error') || title.includes('compile') || title.includes('fix')) {
              labels.push('bug');
            } else if (title.includes('feature') || title.includes('new') || title.includes('add') || title.includes('implement')) {
              labels.push('feature');
            } else if (title.includes('refactor') || title.includes('optimize') || title.includes('improve')) {
              labels.push('refactor');
            } else if (title.includes('build') || title.includes('ci/cd') || title.includes('compile')) {
              labels.push('build');
            } else if (title.includes('doc') || title.includes('readme') || title.includes('wiki')) {
              labels.push('docs');
            } else if (title.includes('test')) {
              labels.push('test');
            }
            
            // Determine priority
            if (title.includes('critical') || title.includes('blocker') || title.includes('urgent')) {
              labels.push('priority-critical');
            } else if (title.includes('high') || title.includes('important')) {
              labels.push('priority-high');
            } else if (title.includes('low') || title.includes('minor') || title.includes('enhancement')) {
              labels.push('priority-low');
            } else {
              labels.push('priority-medium');
            }
            
            return labels.join(',');

      - name: 🏷️ Apply labels
        uses: actions/github-script@v7
        with:
          script: |
            const labels = '${{ steps.labeler.outputs.result }}'.split(',');
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: labels
            });