name: Check Token Permissions

on:
  workflow_dispatch:

jobs:
  check-token:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: 🔐 Test GITHUB_TOKEN permissions
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🔍 Testing token permissions for: $REPO"
          
          # 1. Проверка доступа к репозиторию
          echo "📋 Testing repository access..."
          repo_response=$(curl -s -w "%{http_code}" -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO")
          
          http_code=$(echo "$repo_response" | tail -n1)
          response_body=$(echo "$repo_response" | sed '$d')
          
          if [ "$http_code" = "200" ]; then
            echo "✅ Repository access: OK (200)"
            repo_name=$(echo "$response_body" | jq -r '.full_name')
            echo "📦 Repository: $repo_name"
          else
            echo "❌ Repository access failed: HTTP $http_code"
            echo "Response: $response_body"
            exit 1
          fi
          
          # 2. Проверка прав на создание issue
          echo "📝 Testing issue creation rights..."
          issue_data='{"title":"Test Issue - Please Delete","body":"This is a test issue to check token permissions.","labels":["test"]}'
          
          issue_response=$(curl -s -w "%{http_code}" -X POST \
            -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -d "$issue_data" \
            "https://api.github.com/repos/$REPO/issues")
          
          issue_http_code=$(echo "$issue_response" | tail -n1)
          issue_body=$(echo "$issue_response" | sed '$d')
          
          if [ "$issue_http_code" = "201" ]; then
            echo "✅ Issue creation: OK (201)"
            issue_number=$(echo "$issue_body" | jq -r '.number')
            issue_url=$(echo "$issue_body" | jq -r '.html_url')
            echo "📋 Created test issue: $issue_url"
            
            # Удаляем тестовый issue
            sleep 2
            delete_response=$(curl -s -w "%{http_code}" -X PATCH \
              -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Content-Type: application/json" \
              -d '{"state":"closed"}' \
              "https://api.github.com/repos/$REPO/issues/$issue_number")
            
            if [ "$(echo "$delete_response" | tail -n1)" = "200" ]; then
              echo "✅ Issue closed successfully"
            fi
            
          elif [ "$issue_http_code" = "403" ]; then
            echo "❌ Issue creation: Permission denied (403)"
            echo "ℹ️ Check repository permissions for GITHUB_TOKEN"
          else
            echo "⚠️ Issue creation: HTTP $issue_http_code"
            echo "Response: $issue_body"
          fi
          
          # 3. Проверка прав на метки
          echo "🏷️ Testing label access..."
          labels_response=$(curl -s -w "%{http_code}" -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO/labels?per_page=1")
          
          labels_http_code=$(echo "$labels_response" | tail -n1)
          
          if [ "$labels_http_code" = "200" ]; then
            echo "✅ Labels access: OK (200)"
          elif [ "$labels_http_code" = "403" ]; then
            echo "❌ Labels access: Permission denied (403)"
          else
            echo "⚠️ Labels access: HTTP $labels_http_code"
          fi
          
          echo "🎉 Token check completed!"